"""Core ML storage safety and real converted-model parity. Uses only existing weights."""
import argparse,ctypes as C,hashlib,json,subprocess,signal
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--model',required=True);p.add_argument('--legacy-manifest',required=True);p.add_argument('--output',required=True);a=p.parse_args()
root=Path(__file__).resolve().parents[2];out=Path(a.output).resolve();out.mkdir(parents=True,exist_ok=True)
cli=root/'build/native/turbocider';checks=[];reports={}
def resource(r,expect=True):
 file=out/'resource-request.json';file.write_text(json.dumps(r));done=subprocess.run([str(cli),'coreml',str(file)],capture_output=True,text=True)
 if expect:
  assert done.returncode==0,done.stderr
  return json.loads(done.stdout)
 assert done.returncode!=0,'unsafe request succeeded';return done.stderr
compiled=json.loads((out/'compile-result.json').read_text())['manifest']
reports['inventory']=resource({'action':'inventory','manifest':a.legacy_manifest})
assert sum(e.get('bytes',0) for e in reports['inventory']['entries'] if e.get('category')=='compiled')>1_000_000_000
assert sum(e.get('bytes',0) for e in reports['inventory']['entries'] if e.get('category')=='source')>1_000_000_000
checks.append('external_source_and_compiled_bytes_are_visible')
reports['compile_reuse']=resource({'action':'compile','source_manifest':str(out/'generated/manifest.json'),'cache':str(out/'cache')});assert reports['compile_reuse']['cache_hits']==20;checks.append('twenty_compiled_partitions_reused')
lib=C.CDLL(str(root/'build/native/libturbocider.dylib'));lib.tc_string_free.argtypes=[C.c_void_p];lib.tc_engine_free.argtypes=[C.c_void_p]
lib.tc_engine_create.argtypes=[C.c_char_p,C.POINTER(C.c_void_p),C.POINTER(C.c_void_p)]
lib.tc_engine_generate.argtypes=[C.c_void_p,C.c_char_p,C.c_void_p,C.c_void_p,C.POINTER(C.c_void_p),C.POINTER(C.c_void_p)]
def take(p):
 if not p.value:return ''
 s=C.string_at(p).decode();lib.tc_string_free(p);return s
engine,error=C.c_void_p(),C.c_void_p();assert lib.tc_engine_create(a.model.encode(),C.byref(engine),C.byref(error))==0,take(error)
try:
 for name,manifest in [('converted',compiled),('legacy',a.legacy_manifest)]:
  r={'model':'flux2-klein-4b','prompt':'A red fox in a snowy forest.','width':256,'height':256,'steps':4,'seed':42,'execution':'gpu_ane','allow_approximation':True,'ane_manifest':manifest,'output':str(out/(name+'.png'))}
  result,error=C.c_void_p(),C.c_void_p();code=lib.tc_engine_generate(engine,json.dumps(r).encode(),None,None,C.byref(result),C.byref(error));text,message=take(result),take(error);assert code==0,message;reports[name]=json.loads(text)
finally:lib.tc_engine_free(engine)
assert (out/'converted.png').read_bytes()==(out/'legacy.png').read_bytes(),'converted partitions changed PNG'
checks.append('exported_safetensors_partitions_match_legacy_png');reports['png_sha256']=hashlib.sha256((out/'converted.png').read_bytes()).hexdigest()
# Safety test in synthetic directories, never against the user's original artifacts.
fixture=out/'delete-fixture';fixture.mkdir(exist_ok=True);artifacts={}
for i in range(20):
 directory=fixture/f'{i}.mlpackage';directory.mkdir(exist_ok=True);(directory/'data.bin').write_bytes(b'x');artifacts[str(i)]={'int8_pc':directory.name}
file=fixture/'manifest.json';file.write_text(json.dumps({'artifacts':artifacts}));r={'action':'delete_artifacts','kind':'source','source_manifest':str(file)}
plan=resource(r);assert file.exists();resource(dict(r,apply=True,plan_token='wrong'),False);checks.append('cleanup_preview_and_token_required')
(fixture/'0.mlpackage/data.bin').write_bytes(b'changed');resource(dict(r,apply=True,plan_token=plan['plan_token']),False);checks.append('changed_deletion_plan_rejected')
(fixture/'0.mlpackage/weights.safetensors').write_bytes(b'protect');resource(r,False);(fixture/'0.mlpackage/weights.safetensors').unlink();checks.append('safetensors_deletion_rejected')
plan=resource(r);resource(dict(r,apply=True,plan_token=plan['plan_token']));assert not file.exists();checks.append('only_previewed_sources_removed')
# Remove only the artifacts generated by this validation run, keeping original model/legacy cache.
sentinel=out/'generated/user-file.txt';sentinel.write_text('keep')
for action in [{'action':'delete_artifacts','kind':'source','source_manifest':str(out/'generated/manifest.json')},{'action':'clear_compiled','cache':str(out/'cache')}]:
 plan=resource(action);resource(dict(action,apply=True,plan_token=plan['plan_token']))
assert sentinel.read_text()=='keep' and Path(a.legacy_manifest).exists() and (Path(a.model)/'transformer/diffusion_pytorch_model.safetensors').exists();checks.append('validation_artifacts_released_originals_preserved')
reports['runtime_preview']=resource({'action':'clear_runtime'});checks.append('runtime_cache_preview_without_deletion')
cancel_request=json.loads((out/'export.json').read_text());cancel_request['storage']=str(out/'cancelled-export')
cancel_file=out/'cancel-export.json';cancel_file.write_text(json.dumps(cancel_request))
worker=subprocess.Popen([str(cli),'coreml',str(cancel_file)],stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
assert worker.stderr.readline(),'export did not report progress'
worker.send_signal(signal.SIGINT);_,failure=worker.communicate(timeout=20)
assert worker.returncode==2 and not (out/'cancelled-export/manifest.json').exists(),failure
checks.append('export_cancellation_stops_child_without_manifest')
(out/'report.json').write_text(json.dumps({'passed':True,'checks':checks,'reports':reports},indent=2));print(json.dumps({'passed':True,'checks':checks}))
